name: continous-build
on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
     - main
  workflow_dispatch:
# Testing our first workflow
env: 
  name: Gagandeep
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "hello from $name, job1 of workflow1"
          sleep 30
          hostname
      - name: my step2
        run: |
          echo "hello from $name"
          sleep 10
      - run: |
          echo "hello from step3"
          sleep 10
      - name: my step4 for testing multiple lines of code execution
        run: |
          ls -l
          pwd
          sudo cat /etc/os-release
          uname -a
          echo "final step4 execution done"
  test: 
    runs-on: gagan
    steps:
      - name: step1
        run: |
           echo "hello from $name, job 2 of workflow1"
           sleep 30
           hostname
      - name: my step2
        run: |
          echo "hello from $name"  
          sleep 10

