name: continous-build
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "hello from step1"
          sleep 10
      - name: my step2
        run: |
          echo "$greetings from $name"
          sleep 10
  test: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: step1
        run: |
          echo "hello from step1"
          sleep 10
      - name: my step2
        run: |
          echo "$greetings from $name"
          sleep 10
  deploy: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: step1
        run: |
          echo "hello from step1"
          sleep 10
      - name: my step2
        run: |
          echo "hello from step2"
          sleep 10
  notification-start: 
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "Job started"
          sleep 10
  
        run: |
          echo "$greetings from $name"
          sleep 10
